---
- name: set initial password to new users
  with_items: "{{ _cmd_pveum_user_add.results | json_query('[?item.initial_pwd]') }}"
  become: true
  ansible.builtin.shell: |
    cat <<EOF | pveum passwd {{ item.item.id }}
    {{ item.item.initial_pwd }}
    {{ item.item.initial_pwd }}
    EOF
  no_log: true

- name: set images permissions
  with_items: "{{ _cmd_pve_create_ci_template.results | json_query('[?changed]') }}"
  become: true
  ansible.builtin.file:
    path: "{{ _vz_dirpath }}/images/{{ item.item.name }}.img"
    state: file
    group: "{{ pve_system_group }}"
    mode: 0664
